FROM postgres:17

RUN echo "deb http://deb.debian.org/debian bookworm main contrib non-free" > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y unrar

COPY journeyhub_dump.rar /tmp/journeyhub_dump.rar

RUN unrar x /tmp/journeyhub_dump.rar -d /docker-entrypoint-initdb.d/ && \
    mv /docker-entrypoint-initdb.d/journeyhub_dump.sql /docker-entrypoint-initdb.d/init.sql && \
    rm /tmp/journeyhub_dump.rar

COPY wait-for-db.sh /docker-entrypoint-initdb.d/wait-for-db.sh
RUN chmod +x /docker-entrypoint-initdb.d/wait-for-db.sh