FROM postgres:17


RUN apt-get update && apt-get install -y unzip


COPY journeyhub_dump.zip /tmp/journeyhub_dump.zip


RUN unzip /tmp/journeyhub_dump.zip -d /docker-entrypoint-initdb.d/ && \
                mv /docker-entrypoint-initdb.d/journeyhub_dump.sql /docker-entrypoint-initdb.d/init.sql && \
                rm /tmp/journeyhub_dump.zip


COPY wait-for-db.sh /docker-entrypoint-initdb.d/wait-for-db.sh
RUN chmod +x /docker-entrypoint-initdb.d/wait-for-db.sh